W7D4-new_user_view/sizzler_new_user_view/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, except: [:edit]
end

W7D4-new_user_view/sizzler_new_user_view/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    
    # CRLLL
    # C: current_user
    # R: require_login
    # L: login
    # L: logout
    # L: logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_login
        redirect_to new_session_url unless logged_in?
    end

    def login(user)
        @current_user = user
        session[:session_token] = user.reset_session_token!
    end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end
end

W7D4-new_user_view/sizzler_new_user_view/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
        render :index
    end

    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to users_url
        else
            flash[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def destroy
        @user = User.find(params[:id])
        if user.destroy
            flash[:errors] = ['User destroyed or deleted or something like that']
        else
            render json: @user.errors.full_messages, status: 422
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to "/users/#{@user.id}"
            # render json: user
        else
            render json: @user.errors.full_messages, status: 422
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :country, :age, :password)
    end
end

W7D4-new_user_view/sizzler_new_user_view/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sizzler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
      <%= flash[:errors].join(', ') %>
    <% end %>
    <%= yield %>
  </body>
</html>

W7D4-new_user_view/sizzler_new_user_view/app/views/users/index.html.erb
<h1>Ammunation's VIP Customers</h1>
<% @users.each do |user| %>
    <%= render 'user', user: user, action: :index %>
<% end %>

<a href="<%= new_user_url %>">Create New Account</a>

W7D4-new_user_view/sizzler_new_user_view/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="POST">
    <input type="hidden" 
        name="authenticity_token" 
        value="<%= form_authenticity_token %>">
    
    <label for="user[username]">Username
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>

    <label for="user[email]">Email
        <input type="text" name="user[email]" value="<%= @user.email %>">
    </label>

    <label for="user[country]">Country
        <input type="text" name="user[country]" value="<%= @user.country %>">
    </label>

    <label for="user[age]">Age
        <input type="text" name="user[age]" value="<%= @user.age %>">
    </label>

    <label for="user[password]">Password
        <input type="text" name="user[password]" value="<%= @user.password %>">
    </label>

    <button type="submit">Create New Account</button>
</form>