W7D5-buggy-rails/rails_2_buggy_version/config/routes.rb
Rails.application.routes.draw do
  resources :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :index, :show] do 
    resources :goals, only: [:create]
  end
  resources :goals, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W7D5-buggy-rails/rails_2_buggy_version/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D5-buggy-rails/rails_2_buggy_version/app/models/goal.rb
class Goal < ApplicationRecord
    validates :name, :details, presence: true
    validates :status, inclusion: { in: [:true, :false] }

    belongs_to :user,
    foreign_key: :owner_id,
    class_name: "User"
end

W7D5-buggy-rails/rails_2_buggy_version/app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true
    validates :password, length: { minimum: 6, allow_nill: true }
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true

    has_many :goals, 
    foreign_key: :owner_id,
    class_name: "Goal"

    after_initialize :reset_session_token!

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        return nil if user.nil?
        user.is_password?(password) ? self : nil
    end

    def is_password?(password)
        BCrypt::Password.create(self.password_digest).is_password?(password)
    end
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.new(password)
    end
    
    def reset_session_token!
        self.session_token = SecureRandom.base64(64)
        self.save!
        self.session_token
    end

    private
    def ensure_session_token
        self.session_token ||= SecureRandom.base64(64)
    end
end

W7D5-buggy-rails/rails_2_buggy_version/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  private
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    session[:session_token] = user.reset_session_token!
    current_user = user
  end

  def sign_out!
    @current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_sessions_url unless signed_in?
  end
end

W7D5-buggy-rails/rails_2_buggy_version/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

    before_action :require_signed_in!

    def create
        @goal = Goal.new(goal_params)
        @goal.owner_id = params[:owner_id]

        if @goal.save
            redirect_to user_url(@goal.user)
        else
            flash[:errors] = @goal.errors.full_messages
        end
    end

    def destroy
        @goal = current_user.goals.find_by(id: params[:id])
        if @goal && @goal.delete 
            redirect_to users_url
        end
    end
 
    private

    def goal_params
        params.require(:goal).permit(:name, :details, :status)
    end
    
end

W7D5-buggy-rails/rails_2_buggy_version/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:password],
      params[:user][:username]
    )

    if @user
      sign_in!(@user)
      redirect_to users_url
    else
      flash.now[:errors] = ['Invalid username or password']
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

W7D5-buggy-rails/rails_2_buggy_version/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signed_in!, only: [:show, :index]
  
  def create
    @user = User.new(user_params)
    
    if @user.save!
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  
  def user_params
    params.require(:users).permit(:password, :username)
  end
end

W7D5-buggy-rails/rails_2_buggy_version/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Goal App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

      <% if signed_in? %>
        <nav>
          <a class='button' href="<%= users_url %>">Home</a>
          
          <div>
            <p>Logged in as: <%= current_user.username %></p>
          <form action=<%= session_url %> method='post'>
            <input
              type="hidden"
              name="_method"
              value="delete">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input 
              type="submit" value="Logout">
          </form>
          </div>
        </nav>
      <% end %>

      <% if flash [:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>

    <%= yield %>
  </body>
</html>

W7D5-buggy-rails/rails_2_buggy_version/app/views/users/index.html.erb
<h1>All Users<h2>

<div>
    <h4>list of users</h4>
    <ul> 
        <% @users.each do |user| %>
        <a href=<% user_url(user) %>><li><%=user.username%></li></a>
        <% end %>
    </ul>
</div>

W7D5-buggy-rails/rails_2_buggy_version/app/views/users/new.html.erb
<h1>Welcome!</h1>

<form action=" <%= users_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label>Username:
        <input name ="user[username]" value="<%= @user.username %>">
    </label>
    <label>Password:
        <input name ="user[password]" value="<%= @user.password %>">
    </label>
    <button type="submit">Signup</button>
</form>

W7D5-buggy-rails/rails_2_buggy_version/app/views/users/show.html.erb
<h1>Say hello to <%= @user.username %> </h1>


<div>
    <p>These are @user.username 's Goals: <p>
    <ul>
        <% @user.goals.each do |goal| %>
            <p><%= goal.name %></p>
            <p><%= goal.details %></p>
            <% if goal.status %>
                <p>Done</p>
            <% end %>
            <form action= <%= goal_url %> method="get">
                <input
                type="hidden"
                name="authenticity_token"
                value="<%= form_authenticity_token %>">
                <input type="hidden" name="_method" value="DELETE" />
                <button type="submit">Delete Goal</button>
            </form>
        <% end %>
    </ul>
</div>


<h1>Add a New Goal</h1>

<form action=" <%=user_goals_url(@user)%> " method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label>Name:
        <input name ="goal[name]">
    </label>
    <label>Details:
        <input name ="goal[details]">
    </label>
    <p>Completed?</p>
    <label>True
        <input type="radio" name="goal[status]" value="true">
    </label>
    <label>False
        <input type="radio" name="goal[status]" value="false">
    </label>
    <button type="submit">Create Goal</button>
</form>